### ISSUE TITLE
FEATURE REQUEST- MAKE CLOSE BUTTONS ONE THE LEFT LIKE MACOS

### ISSUE THREAD

**Issue by kb12000** [Hakanbaban53/RealFire#1]
please make the maximize minimize close buttone on the left and make them traffic lights like macos

**Comment by Hakanbaban53** [comment]
I think I can add a script. I will work on it. Thank you for feature idea.

**Comment by kb12000** [comment]
yess your theme is great if you can add these features it will look like safari 15 monterey theme

**Comment by Hakanbaban53** [comment]
windowcontrolmacostheme.uc.js added. you can disable or enable using userchrome manager.

**Comment by kb12000** [comment]
how to get userchrome manager??

**Comment by kb12000** [comment]
tbh idk how to install themes with js and all....i only know to copy and paste css files and folders to chrome folder in profile directory

**Comment by kb12000** [comment]
@Hakanbaban53 can you please guide me ?

**Comment by Hakanbaban53** [comment]
Can you write the operain system?

**Comment by kb12000** [comment]
@Hakanbaban53  I am on windows os…I am getting confused with all the scripts and all
