### ISSUE TITLE
Widen Vertical Tab Bar

### ISSUE THREAD

**Issue by JaxzKyd** [Hakanbaban53/RealFire#10]
Hello! Sorry if this is a dumb question, but is there a way to make the collapsed size of the vertical tab pane wider? For example in the screenshot below the margin on the right side of the bar is significantly smaller than the left side's margins and it has been bugging me
![image](https://github.com/Hakanbaban53/RealFire/assets/39567321/28290487-d060-4e38-9750-e8df1ca86c6d)

**Comment by Hakanbaban53** [comment]
Actually, when I looked carefully, it bothered me. For this, the css part of the vertical Tab Pane.uc.js file needs to be edited. I will send a correction as soon as possible.

**Comment by Hakanbaban53** [comment]
I fixed it. If you think it is not fixed, you can reopen this issue.
