### ISSUE TITLE
...how do i install this theme again?

### ISSUE THREAD

**Issue by JaxzKyd** [Hakanbaban53/RealFire#11]
Funny story... I was in the about:support section to restart my profile right, but i accidentally hit the **refresh** button which... removed all of my stuff, i've been meaning to remake a profile for a while now so i took the opportunity to start fresh. However I have come to the realization that I do not remember how to setup this theme (particularly interested in the vertical tabs pane). I threw all the files from the github into the chrome folder in my new profile, and moved the mozilla.cfg and local-settings.js files to their proper locations, and this is what my browser looks like
![image](https://github.com/Hakanbaban53/RealFire/assets/39567321/59e99548-f30b-4530-8c7d-9160344b5a18)
![image](https://github.com/Hakanbaban53/RealFire/assets/39567321/00e33900-4d86-40fb-bb56-9e1b7ee0b35c)
Any advice on how to set up... anything?

**Comment by Hakanbaban53** [comment]
If you are on Windows, you can reinstall it by running this command:
`curl -sL "https://raw.githubusercontent.com/Hakanbaban53/RealFire/main/programs/install-curl.bat" > %TEMP%\install-curl.bat && %TEMP%\install-curl.bat`

If you are on Linux or MacOS, you can reinstall it by running this command:
`curl -sL "https://raw.githubusercontent.com/Hakanbaban53/RealFire/main/programs/install-curl.bat" > %TEMP%\install-curl.bat && %TEMP%\install-curl.bat`

_The existing files will not cause any problems.  New files will overwrite them._

**Comment by JaxzKyd** [comment]
```
At line:1 char:125
+ ... /main/programs/install-curl.bat" > %TEMP%\install-curl.bat && %TEMP%\ ...
+                                                                ~~
The token '&&' is not a valid statement separator in this version.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidEndOfLine
```

**Comment by Hakanbaban53** [comment]
Can you use cmd instead of powershell?

**Comment by JaxzKyd** [comment]
done, I noticed it applied the theme to the default-release profile, is there a way to put it on a different profile using the installer? Also wasn't there supposed to be a button for the vertical tabs pane in the top bar? If so, it is absent on my install (checked userchrome manager and vertical tabs pane was enabled) 
![image](https://github.com/Hakanbaban53/RealFire/assets/39567321/24d4279f-a7bd-4b3a-b27a-f16409aded23)

**Comment by Hakanbaban53** [comment]
You can use like this:
`curl -sL "https://raw.githubusercontent.com/Hakanbaban53/RealFire/main/programs/install-curl.bat" > %TEMP%\install-curl.bat && %TEMP%\install-curl.bat -p "Your_Custom_Profile_Location"`

**Comment by Hakanbaban53** [comment]
vertical tabs pane only works in stable firefox. I also added a new vertical tabs pane to github called verticalTabsPaneNightly.uc.js. This will also work in firefox nightly.
