### ISSUE TITLE
Okay but what happened to the older RealFire theme? I preferred that one more than this new one

### ISSUE THREAD

**Issue by ahykono** [Hakanbaban53/RealFire#12]
As per title, this isn't the "RealFire" I used to know months ago, it's looks like a totally different theme in the README screenshot & I can't find it no more in FirefoxCss store, seems like it was removed

**Comment by Hakanbaban53** [comment]
If you want to install old theme you can check out the [tags](https://github.com/Hakanbaban53/RealFire/tags).
