### ISSUE TITLE
tab bar / URL bar don't switch places when told to do so by the config.

### ISSUE THREAD

**Issue by mantacid** [Hakanbaban53/RealFire#2]
I'm running firefox version 115.0.1 on Artix Linux. I want the tabs on the left of the screen, as that would make the new tab button closer to the URL bar. 

The issue I am facing is that attempting to do so via `realfire-config.css` does not change the layout (i am setting the relevant value to 3 as instructed by the comments).

**Comment by Hakanbaban53** [comment]
Thanks for reporting this issue. I found the problem. I will fix the problem as soon as possible.

**Comment by Hakanbaban53** [comment]
I fixed that thing. After making the change: Open about:support > Clear startup cache... > Restart
