### ISSUE TITLE
Adaptive Tab Bar Color Compatibility

### ISSUE THREAD

**Issue by bxrlin** [Hakanbaban53/RealFire#3]
So, I wanted to suggest something - how about considering compatibility with the **Adaptive Tab Bar Color** Extension for your theme? This addition could provide an even better browsing experience for your users and cater to those who appreciate both style and functionality.

**Comment by kb12000** [comment]
@Hakanbaban53 yess this will be much appriciated.....it will be icing on the cake.

**Comment by Hakanbaban53** [comment]
Thank you for your suggestion. I may work on it in the future.

**Comment by H1DDENADM1N** [comment]
I did some little modify for support [Adaptive-Tab-Bar-Colour](https://github.com/easonwong-de/Adaptive-Tab-Bar-Colour) 
[includes/realfire-colours.css](https://github.com/Hakanbaban53/RealFire/compare/main...H1DDENADM1N:RealFire:main#diff-eb2ae00d536507e1bb4d96330b2201ceb0e4caee22ff326236f6aaaabca4df4b)
[includes/realfire-tabs.css](https://github.com/Hakanbaban53/RealFire/compare/main...H1DDENADM1N:RealFire:main#diff-255c35e9bcce1558d7ad8e5ca791daafe2629c1e396369a6d9aca7a6136e5684)

**Comment by H1DDENADM1N** [comment]
It looks great.🥰
![RealFire-Theme-and-Adaptive-Tab-Bar-Colour](https://github.com/Hakanbaban53/RealFire/assets/65646535/ac93db90-3b06-4c73-8f2f-7e10d5ee2531)

**Comment by H1DDENADM1N** [comment]
It looks great.🥰
![RealFire-Theme-and-Adaptive-Tab-Bar-Colour](https://github.com/Hakanbaban53/RealFire/assets/65646535/dc56b365-c08d-47d0-b65f-a28031d9f969)

**Comment by Hakanbaban53** [comment]
**wow**, it looks great! Thank you for helping. ❤
