### ISSUE TITLE
vertical tabs version

### ISSUE THREAD

**Issue by featherice** [Hakanbaban53/RealFire#4]
Please add config for sidebery support and hiding horizontal tabs (with windows controls visible)

**Comment by Hakanbaban53** [comment]
İf you want the hide horizonal tab you can use the userChrome manager page and disable Vertical Tabs Pane js. If you wondering how access the userChrome manager with this key combination: `Ctrl+Shift+U`.

**Comment by featherice** [comment]
I think you misunderstood me. I want to have an option where default tabs are neatly hidden like [there](https://github.com/mgastonportillo/gale-for-ff) but with your theme. Tried to do it myself but navbar becomes broken.

**Comment by Hakanbaban53** [comment]
Oh, I got it. I will add this feature as soon as possible.

**Comment by Hakanbaban53** [comment]
I updated it. you can check it out. If there is any other problem please let me know.

**Comment by featherice** [comment]
> I updated it. you can check it out. If there is any other problem please let me know.

![изображение](https://github.com/Hakanbaban53/RealFire/assets/21113334/613a26d3-2886-42f1-8175-685784038820)
Two issues, same issues i bumped into when i was doing it myself:
1. Can't drag window.
2. When isn't maximized navbar becomes crooked like on the screenshot.

**Comment by Hakanbaban53** [comment]
Thank you for reback. I found the problem and solved it. I'm testing it now to see if there are any other problems. I will send the update shortly.

**Comment by Hakanbaban53** [comment]
I updated it. you can check it out. If there is any other problem please let me know.
